---
repos:
  # Backend
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --resolve-all-configs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
      - id: trailing-whitespace
        files: ^((xknx_custom_panel)/.+)?[^/]+\.py$
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.3.5
    hooks:
      # Run `pre-commit run --hook-stage manual python-typing-update --all-files` manually
      # from time to time to update python typing syntax.
      # Will require manual work, before submitting changes!
      - id: python-typing-update
        stages: [manual]
        args:
          - --py39-plus
          - --force
          - --keep-updates
        files: ^(xknx_custom_panel)/.+\.py$
  # Frontend TODO: Move to package json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: src/.
