name: Build

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci && npm install -g @angular/cli
      - run: ng lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci && npm install -g @angular/cli
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci && npm install -g @angular/cli
      - run: xvfb-run --auto-servernum ng test --watch=false --code-coverage=true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          fail_ci_if_error: true
