name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci && npm install -g @angular/cli
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum ng test --watch=false --browsers ChromeHeadless
